/*
    Author - HoverGuy
    Website - https://northernimpulse.com
	
    Defines available gear shops
	
	class YourShopClass - Used as a param for the call, basically the shop you want to display
	{
		conditionToAccess - STRING - Condition that must return either true or false, if true the player will have access to the shop
		
		class ShopCategory - Shop category, can only be Glasses/Headgear/Uniform/Vest/Backpack/MissileLauncher/RocketLauncher/Handgun/AssaultRifle/MachineGun/SubmachineGun/SniperRifle
		{
			content - ARRAY OF ARRAYS - Shop content
			|- 0 - STRING - Classname
			|- 1 - INTEGER - Price
			|- 2 - STRING - Condition that must return either true or false, if true the item appears in the list else no
		};
	};
*/

class HG_DefaultShop // HG_DefaultShop is just a placeholder for testing purposes, you can delete it completely and make your own
{
	conditionToAccess = "true"; // Example: "(playerSide in [west,independent]) AND ((rank player) isEqualTo 'COLONEL')"
	
	class Glasses
	{
		displayName = "$STR_HG_SHOP_FACEWEARS";
		content[] =
		{
			{"G_Aviator", 300, "true"},
			{"CUP_G_RUS_Ratnik_Balaclava_EMR_Summer_1", 300, "true"},
			{"CUP_G_RUS_Ratnik_Balaclava_EMR_Summer_2", 300, "true"},
			{"CUP_G_RUS_Ratnik_Balaclava_EMR_Autumn_1", 300, "true"},
			{"CUP_G_RUS_Ratnik_Balaclava_EMR_Autumn_2", 300, "true"},
			{"CUP_G_RUS_Ratnik_Balaclava_Green_3", 300, "true"},
			{"CUP_G_RUS_Ratnik_Balaclava_Green_2", 300, "true"},
			{"CUP_G_RUS_Ratnik_Balaclava_Green_4", 300, "true"},
			{"CUP_G_RUS_Ratnik_Balaclava_Green_1", 300, "true"},
			{"CUP_G_RUS_Ratnik_Balaclava_Winter_Green_1", 300, "true"},
			{"CUP_G_RUS_Ratnik_Balaclava_Winter_Green_2", 300, "true"},
			{"CUP_G_RUS_Ratnik_Balaclava_Winter_1", 300, "true"},
			{"CUP_G_RUS_Ratnik_Balaclava_Winter_2", 300, "true"},
			{"CUP_G_RUS_Ratnik_Balaclava_Winter_3", 300, "true"},
			{"CUP_G_RUS_Ratnik_Balaclava_Winter_4", 300, "true"},
			{"CUP_G_RUS_Ratnik_Balaclava_Olive_2", 300, "true"},
			{"CUP_G_RUS_Ratnik_Balaclava_Olive_1", 300, "true"},
			{"CUP_G_RUS_Ratnik_Balaclava_Desert_1", 300, "true"},
			{"CUP_G_RUS_Ratnik_Balaclava_Desert_3", 300, "true"},
			{"CUP_G_RUS_Ratnik_Balaclava_Desert_4", 300, "true"},
			{"CUP_G_RUS_Ratnik_Balaclava_Desert_2", 300, "true"},
			{"CUP_G_RUS_Ratnik_Balaclava_Sage_1", 300, "true"},
			{"CUP_G_RUS_Ratnik_Balaclava_Sage_2", 300, "true"},
			{"CUP_G_RUS_Ratnik_Balaclava_A_Tacs_1", 300, "true"},
			{"CUP_G_RUS_Ratnik_Balaclava_A_Tacs_3", 300, "true"},
			{"CUP_G_RUS_Ratnik_Balaclava_A_Tacs_2", 300, "true"},
			{"CUP_G_RUS_Ratnik_Balaclava_A_Tacs_4", 300, "true"},
			{"G_Balaclava_Halloween_01", 300, "true"},
			{"G_Balaclava_combat", 300, "true"},
			{"G_Balaclava_oli", 300, "true"},
			{"G_Balaclava_Flames1", 300, "true"},
			{"G_Balaclava_lowprofile", 300, "true"},
			{"G_Balaclava_Scarecrow_01", 300, "true"},
			{"G_Balaclava_Tropentarn", 300, "true"},
			{"G_Balaclava_Flecktarn", 300, "true"},
			{"G_Balaclava_BlueStrips", 300, "true"},
			{"G_Balaclava_Skull1", 300, "true"},
			{"G_Balaclava_blk", 300, "true"},
			{"G_Bandanna_aviator", 300, "true"},
			{"G_Bandanna_Vampire_01", 300, "true"},
			{"G_Bandanna_beast", 300, "true"},
			{"G_Bandanna_CandySkull", 300, "true"},
			{"G_Bandanna_tan", 300, "true"},
			{"G_Bandanna_RedFlame1", 300, "true"},
			{"G_Bandanna_oli", 300, "true"},
			{"G_Bandanna_OrangeFlame1", 300, "true"},
			{"G_Bandanna_BlueFlame2", 300, "true"},
			{"G_Bandanna_BlueFlame1", 300, "true"},
			{"G_Bandanna_sport", 300, "true"},
			{"G_Bandanna_shades", 300, "true"},
			{"G_Bandanna_khk", 300, "true"},
			{"G_Bandanna_Skull1", 300, "true"},
			{"G_Bandanna_Syndikat1", 300, "true"},
			{"G_Bandanna_Skull2", 300, "true"},
			{"G_Bandanna_blk", 300, "true"},
			{"G_Combat", 300, "true"},
			{"CUP_G_RUS_Ratnik_6M2_Desert", 300, "true"},
			{"CUP_G_RUS_Ratnik_6M2_Summer", 300, "true"},
			{"CUP_G_RUS_Ratnik_6M21_Summer", 300, "true"},
			{"CUP_G_RUS_Ratnik_6M21_Desert", 300, "true"},
			{"G_Squares_Tinted", 300, "true"},
			{"G_Squares", 300, "true"},
			{"nan", 300, "true"},
			{"CUP_RUS_Balaclava_blk", 300, "true"},
			{"CUP_RUS_Balaclava_emr", 300, "true"},
			{"CUP_RUS_Balaclava_grn", 300, "true"},
			{"CUP_RUS_Balaclava_rgr", 300, "true"},
			{"CUP_RUS_Balaclava_tan", 300, "true"},
			{"CUP_Beard_Black", 300, "true"},
			{"CUP_Beard_Blonde", 300, "true"},
			{"CUP_Beard_Brown", 300, "true"},
			{"CUP_G_ESS_BLK_Dark", 300, "true"},
			{"CUP_G_ESS_BLK_Ember", 300, "true"},
			{"CUP_G_ESS_BLK", 300, "true"},
			{"CUP_G_ESS_CBR_Dark", 300, "true"},
			{"CUP_G_ESS_CBR_Ember", 300, "true"},
			{"CUP_G_ESS_CBR", 300, "true"},
			{"CUP_G_ESS_RGR_Dark", 300, "true"},
			{"CUP_G_ESS_RGR_Ember", 300, "true"},
			{"CUP_G_ESS_RGR", 300, "true"},
			{"CUP_G_ESS_KHK_Dark", 300, "true"},
			{"CUP_G_ESS_KHK_Ember", 300, "true"},
			{"CUP_G_ESS_KHK", 300, "true"},
			{"CUP_G_ESS_BLK_Facewrap_Black", 300, "true"},
			{"CUP_G_ESS_RGR_Facewrap_Ranger", 300, "true"},
			{"CUP_G_ESS_CBR_Facewrap_Red", 300, "true"},
			{"CUP_G_ESS_RGR_Facewrap_Skull", 300, "true"},
			{"CUP_G_ESS_KHK_Facewrap_Tan", 300, "true"},
			{"CUP_G_ESS_RGR_Facewrap_Tropical", 300, "true"},
			{"CUP_G_ESS_KHK_Facewrap_White", 300, "true"},
			{"CUP_G_ESS_BLK_Facewrap_Black_GPS", 300, "true"},
			{"CUP_G_ESS_BLK_Scarf_Blk", 300, "true"},
			{"CUP_G_ESS_BLK_Scarf_Grn", 300, "true"},
			{"CUP_G_ESS_BLK_Scarf_Red", 300, "true"},
			{"CUP_G_ESS_KHK_Scarf_Tan", 300, "true"},
			{"CUP_G_ESS_BLK_Scarf_White", 300, "true"},
			{"CUP_G_ESS_BLK_Scarf_Face_Blk", 300, "true"},
			{"CUP_G_ESS_BLK_Scarf_Face_Grn", 300, "true"},
			{"CUP_G_ESS_BLK_Scarf_Face_Red", 300, "true"},
			{"CUP_G_ESS_KHK_Scarf_Face_Tan", 300, "true"},
			{"CUP_G_ESS_BLK_Scarf_Face_White", 300, "true"},
			{"CUP_G_ESS_BLK_Scarf_Blk_Beard", 300, "true"},
			{"CUP_G_ESS_BLK_Scarf_Blk_Beard_Blonde", 300, "true"},
			{"CUP_G_ESS_BLK_Scarf_Grn_Beard", 300, "true"},
			{"CUP_G_ESS_BLK_Scarf_Grn_Beard_Blonde", 300, "true"},
			{"CUP_G_ESS_BLK_Scarf_Red_Beard", 300, "true"},
			{"CUP_G_ESS_BLK_Scarf_Red_Beard_Blonde", 300, "true"},
			{"CUP_G_ESS_KHK_Scarf_Tan_Beard", 300, "true"},
			{"CUP_G_ESS_KHK_Scarf_Tan_Beard_Blonde", 300, "true"},
			{"CUP_G_ESS_BLK_Scarf_White_Beard", 300, "true"},
			{"CUP_G_ESS_BLK_Scarf_White_Beard_Blonde", 300, "true"},
			{"CUP_G_ESS_BLK_Scarf_Grn_GPS", 300, "true"},
			{"CUP_G_ESS_KHK_Scarf_Tan_GPS", 300, "true"},
			{"CUP_G_ESS_BLK_Scarf_White_GPS", 300, "true"},
			{"CUP_G_ESS_BLK_Scarf_Face_Grn_GPS", 300, "true"},
			{"CUP_G_ESS_KHK_Scarf_Face_Tan_GPS", 300, "true"},
			{"CUP_G_ESS_BLK_Scarf_Face_White_GPS", 300, "true"},
			{"CUP_G_ESS_BLK_Scarf_Grn_GPS_Beard_Blonde", 300, "true"},
			{"CUP_G_ESS_BLK_Scarf_Grn_GPS_Beard", 300, "true"},
			{"CUP_G_ESS_KHK_Scarf_Tan_GPS_Beard", 300, "true"},
			{"CUP_G_ESS_KHK_Scarf_Tan_GPS_Beard_Blonde", 300, "true"},
			{"CUP_G_ESS_BLK_Scarf_White_GPS_Beard", 300, "true"},
			{"CUP_G_ESS_BLK_Scarf_White_GPS_Beard_Blonde", 300, "true"},
			{"CUP_G_PMC_Facewrap_Black_Glasses_Dark_Headset", 300, "true"},
			{"CUP_G_PMC_Facewrap_Black_Glasses_Dark", 300, "true"},
			{"CUP_G_PMC_Facewrap_Black_Glasses_Ember", 300, "true"},
			{"CUP_PMC_Facewrap_Black", 300, "true"},
			{"CUP_PMC_Facewrap_Ranger", 300, "true"},
			{"CUP_PMC_Facewrap_Red", 300, "true"},
			{"CUP_PMC_Facewrap_Skull", 300, "true"},
			{"CUP_PMC_Facewrap_Smilie", 300, "true"},
			{"CUP_G_PMC_Facewrap_Tan_Glasses_Dark_Headset", 300, "true"},
			{"CUP_G_PMC_Facewrap_Tan_Glasses_Dark", 300, "true"},
			{"CUP_G_PMC_Facewrap_Tan_Glasses_Ember", 300, "true"},
			{"CUP_PMC_Facewrap_Tan", 300, "true"},
			{"CUP_G_PMC_Facewrap_Tropical_Glasses_Dark_Headset", 300, "true"},
			{"CUP_G_PMC_Facewrap_Tropical_Glasses_Dark", 300, "true"},
			{"CUP_G_PMC_Facewrap_Tropical_Glasses_Ember", 300, "true"},
			{"CUP_PMC_Facewrap_Tropical", 300, "true"},
			{"CUP_G_PMC_Facewrap_Winter_Glasses_Dark_Headset", 300, "true"},
			{"CUP_G_PMC_Facewrap_Winter_Glasses_Dark", 300, "true"},
			{"CUP_G_PMC_Facewrap_Winter_Glasses_Ember", 300, "true"},
			{"CUP_PMC_Facewrap_Winter", 300, "true"},
			{"CUP_G_GPS", 300, "true"},
			{"CUP_G_Grn_Scarf_Shades_GPS", 300, "true"},
			{"CUP_G_Tan_Scarf_Shades_GPS", 300, "true"},
			{"CUP_G_White_Scarf_Shades_GPS", 300, "true"},
			{"CUP_G_Grn_Scarf_Shades_GPS_Beard", 300, "true"},
			{"CUP_G_Tan_Scarf_Shades_GPS_Beard", 300, "true"},
			{"CUP_G_Tan_Scarf_Shades_GPS_Beard_Blonde", 300, "true"},
			{"CUP_G_White_Scarf_Shades_GPS_Beard", 300, "true"},
			{"CUP_G_White_Scarf_Shades_GPS_Beard_Blonde", 300, "true"},
			{"CUP_G_PMC_RadioHeadset_Glasses_Dark", 300, "true"},
			{"CUP_G_PMC_RadioHeadset_Glasses_Ember", 300, "true"},
			{"CUP_G_PMC_RadioHeadset_Glasses", 300, "true"},
			{"CUP_G_PMC_RadioHeadset", 300, "true"},
			{"CUP_TK_NeckScarf", 300, "true"},
			{"CUP_G_Scarf_Face_Blk", 300, "true"},
			{"CUP_G_Scarf_Face_Grn", 300, "true"},
			{"CUP_G_Scarf_Face_Red", 300, "true"},
			{"CUP_G_Scarf_Face_Tan", 300, "true"},
			{"CUP_G_Scarf_Face_White", 300, "true"},
			{"CUP_G_Oakleys_Clr", 300, "true"},
			{"CUP_G_Oakleys_Drk", 300, "true"},
			{"CUP_G_Oakleys_Embr", 300, "true"},
			{"CUP_G_TK_RoundGlasses", 300, "true"},
			{"CUP_G_TK_RoundGlasses_blk", 300, "true"},
			{"CUP_G_TK_RoundGlasses_gold", 300, "true"},
			{"CUP_G_Grn_Scarf_Shades", 300, "true"},
			{"CUP_G_Tan_Scarf_Shades", 300, "true"},
			{"CUP_G_White_Scarf_Shades", 300, "true"},
			{"CUP_G_Grn_Scarf_Shades_Beard", 300, "true"},
			{"CUP_G_Grn_Scarf_Shades_Beard_Blonde", 300, "true"},
			{"CUP_G_Tan_Scarf_Shades_Beard", 300, "true"},
			{"CUP_G_Tan_Scarf_Shades_Beard_Blonde", 300, "true"},
			{"CUP_G_White_Scarf_Shades_Beard_Blonde", 300, "true"},
			{"CUP_G_White_Scarf_Shades_Beard", 300, "true"},
			{"CUP_G_Beard_Shades_Black", 300, "true"},
			{"CUP_G_Beard_Shades_Blonde", 300, "true"},
			{"CUP_FR_NeckScarf3", 300, "true"},
			{"CUP_FR_NeckScarf", 300, "true"},
			{"CUP_FR_NeckScarf2", 300, "true"},
			{"CUP_FR_NeckScarf5", 300, "true"},
			{"CUP_FR_NeckScarf4", 300, "true"},
			{"CUP_G_WatchGPSCombo", 300, "true"},
			{"CUP_G_Grn_Scarf_GPS", 300, "true"},
			{"CUP_G_Tan_Scarf_GPS", 300, "true"},
			{"CUP_G_White_Scarf_GPS", 300, "true"},
			{"CUP_G_Grn_Scarf_GPS_Beard_Blonde", 300, "true"},
			{"CUP_G_Grn_Scarf_GPS_Beard", 300, "true"},
			{"CUP_G_Tan_Scarf_GPS_Beard", 300, "true"},
			{"CUP_G_Tan_Scarf_GPS_Beard_Blonde", 300, "true"},
			{"CUP_G_White_Scarf_GPS_Beard", 300, "true"},
			{"CUP_G_White_Scarf_GPS_Beard_Blonde", 300, "true"},
			{"CUP_G_Grn_Scarf_Shades_GPSCombo", 300, "true"},
			{"CUP_G_Tan_Scarf_Shades_GPSCombo", 300, "true"},
			{"CUP_G_White_Scarf_Shades_GPSCombo", 300, "true"},
			{"CUP_G_Grn_Scarf_Shades_GPSCombo_Beard", 300, "true"},
			{"CUP_G_Grn_Scarf_Shades_GPSCombo_Beard_Blonde", 300, "true"},
			{"CUP_G_Tan_Scarf_Shades_GPSCombo_Beard_Blonde", 300, "true"},
			{"CUP_G_Tan_Scarf_Shades_GPSCombo_Beard", 300, "true"},
			{"CUP_G_White_Scarf_Shades_GPSCombo_Beard_Blonde", 300, "true"},
			{"CUP_G_White_Scarf_Shades_GPSCombo_Beard", 300, "true"},
			{"CUP_G_WristWatch", 300, "true"}
		};
	};
	
	class Headgear
	{
		displayName = "$STR_HG_SHOP_HEADGEARS";
		content[] =
		{
			{"H_HelmetB_light_grass",1500,"true"}
	    };
	};
	
	class Uniform
	{
		displayName = "$STR_HG_SHOP_UNIFORMS";
		content[] =
		{
		    {"CUP_U_CRYE_G3C_MC_V3", 500, "true"},
			{"CUP_U_CRYE_G3C_MC", 500, "true"},
			{"CUP_I_B_PMC_Unit_20", 400, "true"},
			{"CUP_I_B_PMC_Unit_22", 400, "true"},
			{"CUP_I_B_PMC_Unit_21", 400, "true"},
			{"CUP_I_B_PMC_Unit_19", 400, "true"},
			{"CUP_I_B_PMC_Unit_17", 400, "true"},
			{"CUP_I_B_PMC_Unit_13", 400, "true"},
			{"CUP_I_B_PMC_Unit_14", 400, "true"},
			{"CUP_I_B_PMC_Unit_16", 400, "true"},
			{"CUP_I_B_PMC_Unit_15", 400, "true"},
			{"CUP_I_B_PMC_Unit_12", 400, "true"},
			{"CUP_I_B_PMC_Unit_3", 400, "true"},
			{"CUP_I_B_PMC_Unit_2", 400, "true"},
			{"CUP_I_B_PMC_Unit_1", 400, "true"},
			{"CUP_I_B_PMC_Unit_4", 400, "true"},
			{"CUP_I_B_PMC_Unit_7", 400, "true"},
			{"CUP_I_B_PMC_Unit_6", 400, "true"},
			{"CUP_I_B_PMC_Unit_5", 400, "true"},
			{"CUP_I_B_PMC_Unit_8", 400, "true"},
			{"CUP_I_B_PMC_Unit_11", 400, "true"},
			{"CUP_I_B_PMC_Unit_10", 400, "true"},
			{"CUP_I_B_PMC_Unit_9", 400, "true"},
			{"CUP_I_B_PMC_Unit_42", 400, "true"},
			{"CUP_I_B_PMC_Unit_41", 400, "true"},
			{"CUP_I_B_PMC_Unit_43", 400, "true"},
			{"CUP_I_B_PMC_Unit_40", 400, "true"},
			{"CUP_I_B_PMC_Unit_39", 400, "true"},
			{"CUP_I_B_PMC_Unit_36", 400, "true"},
			{"CUP_I_B_PMC_Unit_38", 400, "true"},
			{"CUP_I_B_PMC_Unit_37", 400, "true"},
			{"CUP_I_B_PMC_Unit_28", 400, "true"},
			{"CUP_I_B_PMC_Unit_24", 400, "true"},
			{"CUP_I_B_PMC_Unit_23", 400, "true"},
			{"CUP_I_B_PMC_Unit_35", 400, "true"},
			{"CUP_I_B_PMC_Unit_31", 400, "true"},
			{"CUP_I_B_PMC_Unit_32", 400, "true"},
			{"CUP_I_B_PMC_Unit_29", 400, "true"},
			{"CUP_I_B_PMC_Unit_26", 400, "true"},
			{"CUP_I_B_PMC_Unit_30", 400, "true"},
			{"CUP_I_B_PMC_Unit_27", 400, "true"},
			{"CUP_I_B_PMC_Unit_25", 400, "true"},
			{"CUP_I_B_PMC_Unit_34", 400, "true"},
			{"CUP_I_B_PMC_Unit_18", 400, "true"},
			{"CUP_I_B_PMC_Unit_33", 400, "true"},
			{"CUP_U_O_RUS_Gorka_Green", 700, "true"},
			{"CUP_U_O_RUS_Gorka_Partizan", 700, "true"},
			{"CUP_U_O_RUS_Gorka_Partizan_gloves2", 700, "true"},
			{"CUP_U_O_RUS_Gorka_Partizan_gloves_kneepads", 700, "true"},
			{"CUP_U_O_RUS_Gorka_Partizan_A", 700, "true"},
			{"CUP_U_O_RUS_Gorka_Partizan_A_gloves2", 700, "true"},
			{"CUP_U_O_RUS_Gorka_Partizan_A_gloves_kneepads", 700, "true"},
			{"CUP_U_O_RUS_Gorka_Green_gloves2", 700, "true"},
			{"CUP_U_O_RUS_Gorka_Green_gloves_kneepads", 700, "true"},
			{"CUP_U_O_RUS_Soldier_Gorka_EMR_1", 700, "true"},
			{"CUP_U_O_RUS_Soldier_Gorka_EMR_3", 700, "true"},
			{"CUP_U_O_RUS_Soldier_Gorka_EMR_4", 700, "true"},
			{"CUP_U_O_RUS_Soldier_Gorka_EMR_2", 700, "true"},
			{"CUP_U_O_RUS_Soldier_Gorka_Yellow_1", 700, "true"},
			{"CUP_U_O_RUS_Soldier_Gorka_Yellow_3", 700, "true"},
			{"CUP_U_O_RUS_Soldier_Gorka_Yellow_4", 700, "true"},
			{"CUP_U_O_RUS_Soldier_Gorka_Yellow_2", 700, "true"},
			{"CUP_U_O_RUS_Soldier_Gorka_Brown_1", 700, "true"},
			{"CUP_U_O_RUS_Soldier_Gorka_Brown_3", 700, "true"},
			{"CUP_U_O_RUS_Soldier_Gorka_Brown_4", 700, "true"},
			{"CUP_U_O_RUS_Soldier_Gorka_Brown_2", 700, "true"},
			{"CUP_U_O_RUS_Soldier_Gorka_Khaki_1", 700, "true"},
			{"CUP_U_O_RUS_Soldier_Gorka_Khaki_3", 700, "true"},
			{"CUP_U_O_RUS_Soldier_Gorka_Khaki_4", 700, "true"},
			{"CUP_U_O_RUS_Soldier_Gorka_Khaki_2", 700, "true"},
			{"CUP_U_O_RUS_Soldier_Gorka_A_Tacs_1", 700, "true"},
			{"CUP_U_O_RUS_Soldier_Gorka_A_Tacs_3", 700, "true"},
			{"CUP_U_O_RUS_Soldier_Gorka_A_Tacs_4", 700, "true"},
			{"CUP_U_O_RUS_Soldier_Gorka_A_Tacs_2", 700, "true"},
			{"CUP_U_O_RUS_Soldier_Reversible_Suit_6Sh122_Summer_1", 500, "true"},
			{"CUP_U_O_RUS_Soldier_Reversible_Suit_6Sh122_Summer_3", 500, "true"},
			{"CUP_U_O_RUS_Soldier_Reversible_Suit_6Sh122_Summer_4", 500, "true"},
			{"CUP_U_O_RUS_Soldier_Reversible_Suit_6Sh122_Summer_2", 500, "true"},
			{"CUP_U_O_RUS_Soldier_Reversible_Suit_6Sh122_Autumn_1", 500, "true"},
			{"CUP_U_O_RUS_Soldier_Reversible_Suit_6Sh122_Autumn_3", 500, "true"},
			{"CUP_U_O_RUS_Soldier_Reversible_Suit_6Sh122_Autumn_4", 500, "true"},
			{"CUP_U_O_RUS_Soldier_Reversible_Suit_6Sh122_Autumn_2", 500, "true"},
			{"CUP_U_O_RUS_M88_MSV_rolled_up", 300, "true"},
			{"CUP_U_O_RUS_M88_VDV_rolled_up", 300, "true"},
			{"CUP_U_O_RUS_M88_VDV", 300, "true"},
			{"CUP_U_O_RUS_M88_MSV", 300, "true"}
		};
	};
	
	class Vest
	{
		displayName = "$STR_HG_SHOP_VESTS";
		content[] =
		{
		    {"V_PlateCarrierGL_mtp",500,"true"}
		};
	};
	
	class Backpack
	{
		displayName = "$STR_HG_SHOP_BACKPACKS";
		content[] =
		{
			{"B_Carryall_oucamo",800,"true"}
		};
	};
	
	class MissileLauncher
	{
		displayName = "$STR_HG_SHOP_MISSILE_LAUNCHER";
		content[] =
		{
			{"launch_B_Titan_F",50000,"true"}
		};
	};
	
	class RocketLauncher
	{
		displayName = "$STR_HG_SHOP_ROCKET_LAUNCHER";
		content[] =
		{
			{"launch_RPG7_F",50000,"true"}
		};
	};
	
	class Handgun
	{
		displayName = "$STR_HG_SHOP_HANDGUN";
		content[] =
		{
			{"hgun_P07_F",1500,"true"}
		};
	};
	
	class AssaultRifle
	{
		displayName = "$STR_HG_SHOP_ASSAULT_RIFLE";
		content[] =
		{
			{"TR_CXS_Baglama", 6, "true"},
			{"USSR_GuitarA", 10, "true"},
			{"CUP_arifle_Sa58P", 50, "true"},
			{"CUP_arifle_Sa58P_wood", 55, "true"},
			{"CUP_arifle_Sa58P_woodland", 55, "true"},
			{"CUP_arifle_Sa58P_des", 55, "true"},
			{"CUP_arifle_Sa58P_rearris", 250, "true"},
			{"CUP_arifle_Sa58P_frontris_woodland", 300, "true"},
			{"CUP_arifle_Sa58P_frontris_desert", 300, "true"},
			{"CUP_arifle_Sa58P_RIS1", 500, "true"},
			{"CUP_arifle_Sa58P_frontris", 300, "true"},
			{"CUP_arifle_Sa58s", 40, "true"},
			{"CUP_arifle_Sa58Pi", 45, "true"},
			{"CUP_arifle_Sa58s_rearris", 60, "true"},
			{"CUP_arifle_Sa58V", 40, "true"},
			{"CUP_arifle_Sa58V_wood", 44, "true"},
			{"CUP_arifle_Sa58V_woodland", 44, "true"},
			{"CUP_arifle_Sa58V_rearris", 60, "true"},
			{"CUP_arifle_Sa58V_camo", 44, "true"},
			{"CUP_arifle_Sa58V_frontris", 60, "true"},
			{"CUP_arifle_Sa58RIS1", 150, "true"},
			{"CUP_arifle_Sa58RIS1_woodland", 200, "true"},
			{"CUP_arifle_Sa58RIS1_des", 200, "true"},
			{"CUP_arifle_Sa58RIS2", 300, "true"},
			{"CUP_arifle_Sa58RIS2_camo", 300, "true"},
			{"CUP_arifle_Sa58RIS2_gl", 320, "true"},
			{"CUP_arifle_Sa58RIS2_woodland", 300, "true"},
			{"CUP_arifle_Sa58RIS2_gl_woodland", 300, "true"},
			{"CUP_arifle_Sa58RIS2_gl_desert", 320, "true"},
			{"CUP_arifle_AKM", 200, "true"},
			{"CUP_arifle_AKM_GL", 300, "true"},
			{"CUP_arifle_AKM_GL_top_rail", 1500, "true"},
			{"CUP_arifle_AKMN_railed", 3000, "true"},
			{"CUP_arifle_AKMN_railed_desert", 3000, "true"},
			{"CUP_arifle_AKMN_railed_afg", 3000, "true"},
			{"CUP_arifle_AKMN_railed_afg_desert", 3000, "true"},
			{"CUP_arifle_AKM_top_rail", 1500, "true"},
			{"CUP_arifle_AKMS", 250, "true"},
			{"CUP_arifle_AKMS_GL", 350, "true"},
			{"CUP_arifle_AKMS_top_rail", 3000, "true"},
			{"CUP_arifle_AKMS_GL_top_rail", 3500, "true"},
			{"CUP_arifle_AKMS_Early", 300, "true"},
			{"CUP_arifle_AKMS_GL_Early", 350, "true"},
			{"CUP_arifle_AKM_GL_Early", 350, "true"},
			{"CUP_arifle_AKM_Early", 300, "true"},
			{"CUP_arifle_AK47", 150, "true"},
			{"CUP_arifle_AK47_GL", 250, "true"},
			{"CUP_arifle_AK47_GL_top_rail", 1400, "true"},
			{"CUP_arifle_AK47_top_rail", 1200, "true"},
			{"CUP_arifle_AKS", 150, "true"},
			{"CUP_arifle_AKS_top_rail", 1150, "true"},
			{"CUP_arifle_AKS74", 300, "true"},
			{"CUP_arifle_AKS74_GL", 450, "true"},
			{"CUP_arifle_AKS74_GL_top_rail", 1400, "true"},
			{"CUP_arifle_AKS74_top_rail", 1200, "true"},
			{"CUP_arifle_AKS74U", 150, "true"},
			{"CUP_arifle_AKS74U_railed", 3000, "true"},
			{"CUP_arifle_AKS74U_top_rail", 1100, "true"},
			{"CUP_arifle_AKS74_Early", 300, "true"},
			{"CUP_arifle_AKS74_GL_Early", 450, "true"},
			{"CUP_arifle_AK47_Early", 150, "true"},
			{"CUP_arifle_AK47_GL_Early", 250, "true"},
			{"CUP_arifle_AK101", 400, "true"},
			{"CUP_arifle_AK101_GL", 550, "true"},
			{"CUP_arifle_AK101_GL_railed", 3400, "true"},
			{"CUP_arifle_AK101_GL_top_rail", 1400, "true"},
			{"CUP_arifle_AK101_railed", 3200, "true"},
			{"CUP_arifle_AK101_top_rail", 1200, "true"},
			{"CUP_arifle_AK102", 400, "true"},
			{"CUP_arifle_AK102_railed", 3200, "true"},
			{"CUP_arifle_AK102_top_rail", 1200, "true"},
			{"CUP_arifle_AK103", 500, "true"},
			{"CUP_arifle_AK103_GL", 650, "true"},
			{"CUP_arifle_AK103_GL_railed", 3650, "true"},
			{"CUP_arifle_AK103_GL_top_rail", 1650, "true"},
			{"CUP_arifle_AK103_railed", 3500, "true"},
			{"CUP_arifle_AK103_top_rail", 1500, "true"},
			{"CUP_arifle_AK104", 400, "true"},
			{"CUP_arifle_AK104_railed", 3400, "true"},
			{"CUP_arifle_AK104_top_rail", 1400, "true"},
			{"CUP_arifle_AK105", 400, "true"},
			{"CUP_arifle_AK105_railed", 3400, "true"},
			{"CUP_arifle_AK105_top_rail", 1400, "true"},
			{"CUP_arifle_AK107", 900, "true"},
			{"CUP_arifle_AK107_GL", 1150, "true"},
			{"CUP_arifle_AK107_GL_railed", 4200, "true"},
			{"CUP_arifle_AK107_GL_top_rail", 2100, "true"},
			{"CUP_arifle_AK107_railed", 3800, "true"},
			{"CUP_arifle_AK107_top_rail", 1800, "true"},
			{"CUP_arifle_AK108", 950, "true"},
			{"CUP_arifle_AK108_GL", 1200, "true"},
			{"CUP_arifle_AK108_GL_railed", 4200, "true"},
			{"CUP_arifle_AK108_GL_top_rail", 2100, "true"},
			{"CUP_arifle_AK108_railed", 3800, "true"},
			{"CUP_arifle_AK108_top_rail", 1800, "true"},
			{"CUP_arifle_AK109", 950, "true"},
			{"CUP_arifle_AK109_GL", 1200, "true"},
			{"CUP_arifle_AK109_GL_railed", 4200, "true"},
			{"CUP_arifle_AK109_GL_top_rail", 2100, "true"},
			{"CUP_arifle_AK109_railed", 3800, "true"},
			{"CUP_arifle_AK109_top_rail", 1800, "true"},
			{"CUP_arifle_AK74M", 300, "true"},
			{"CUP_arifle_AK74M_GL", 550, "true"},
			{"CUP_arifle_AK74M_GL_railed_desert", 2550, "true"},
			{"CUP_arifle_AK74M_GL_railed", 3550, "true"},
			{"CUP_arifle_AK74M_GL_railed_camo", 2550, "true"},
			{"CUP_arifle_AK74M_GL_camo", 550, "true"},
			{"CUP_arifle_AK74M_GL_desert", 550, "true"},
			{"CUP_arifle_AK74M_GL_top_rail_desert", 1550, "true"},
			{"CUP_arifle_AK74M_GL_top_rail", 1550, "true"},
			{"CUP_arifle_AK74M_GL_top_rail_camo", 1550, "true"},
			{"CUP_arifle_AK74M_railed_camo", 3500, "true"},
			{"CUP_arifle_AK74M_railed_desert", 3500, "true"},
			{"CUP_arifle_AK74M_railed_afg_desert", 3500, "true"},
			{"CUP_arifle_AK74M_railed", 3500, "true"},
			{"CUP_arifle_AK74M_railed_afg", 3500, "true"},
			{"CUP_arifle_AK74M_railed_afg_camo", 3500, "true"},
			{"CUP_arifle_AK74M_desert", 300, "true"},
			{"CUP_arifle_AK74M_top_rail_camo", 1300, "true"},
			{"CUP_arifle_AK74M_top_rail_desert", 1300, "true"},
			{"CUP_arifle_AK74M_camo", 300, "true"},
			{"CUP_arifle_AK74", 200, "true"},
			{"CUP_arifle_AK74_GL", 350, "true"},
			{"CUP_arifle_AK74M_top_rail", 1300, "true"},
			{"CUP_arifle_AK74_top_rail", 1200, "true"},
			{"CUP_arifle_AK74_GL_top_rail", 1350, "true"},
			{"CUP_arifle_AK74_Early", 150, "true"},
			{"CUP_arifle_AK74_GL_Early", 200, "true"},
			{"CUP_arifle_AS_VAL", 2500, "true"},
			{"CUP_arifle_AS_VAL_VFG", 2600, "true"},
			{"CUP_arifle_AS_VAL_flash", 2600, "true"},
			{"CUP_arifle_OTS14_GROZA_762_GL", 2300, "true"},
			{"CUP_arifle_OTS14_GROZA_762_Grip", 2000, "true"},
			{"CUP_arifle_OTS14_GROZA_762", 3000, "true"},
			{"CUP_arifle_OTS14_GROZA_GL", 2000, "true"},
			{"CUP_arifle_OTS14_GROZA_Grip", 1800, "true"},
			{"CUP_arifle_OTS14_GROZA", 2700, "true"},
			{"CUP_arifle_TYPE_56_2_Early", 100, "true"},
			{"CUP_arifle_TYPE_56_2", 150, "true"},
			{"CUP_arifle_TYPE_56_2_top_rail", 400, "true"},
			{"CUP_arifle_AK12_black", 1200, "true"},
			{"CUP_arifle_AK12_AFG_arid", 1300, "true"},
			{"CUP_arifle_AK12_AFG_lush", 1300, "true"},
			{"CUP_arifle_AK12_AFG_tan", 1300, "true"},
			{"CUP_arifle_AK12_AFG_snowtiger", 1300, "true"},
			{"CUP_arifle_AK12_AFG_tiger", 1300, "true"},
			{"CUP_arifle_AK12_AFG_winter", 1300, "true"},
			{"CUP_arifle_AK12_AFG_wood", 1300, "true"},
			{"CUP_arifle_AK12_AFG_bicolor", 1300, "true"},
			{"CUP_arifle_AK12_AFG_black", 1300, "true"},
			{"CUP_arifle_AK12_arid", 1200, "true"},
			{"CUP_arifle_AK12_VG_arid", 1400, "true"},
			{"CUP_arifle_AK12_VG_lush", 1400, "true"},
			{"CUP_arifle_AK12_VG_tan", 1400, "true"},
			{"CUP_arifle_AK12_VG_snowtiger", 1400, "true"},
			{"CUP_arifle_AK12_VG_tiger", 1400, "true"},
			{"CUP_arifle_AK12_VG_bicolor", 1400, "true"},
			{"CUP_arifle_AK12_VG_winter", 1400, "true"},
			{"CUP_arifle_AK12_VG_wood", 1400, "true"},
			{"CUP_arifle_AK12_VG_black", 1400, "true"},
			{"CUP_arifle_AK12_lush", 1200, "true"},
			{"CUP_arifle_AK12_tan", 1200, "true"},
			{"CUP_arifle_AK12_snowtiger", 1200, "true"},
			{"CUP_arifle_AK12_tiger", 1200, "true"},
			{"CUP_arifle_AK12_bicolor", 1200, "true"},
			{"CUP_arifle_AK12_winter", 1200, "true"},
			{"CUP_arifle_AK12_wood", 1200, "true"},
			{"CUP_arifle_AK12_GP34_black", 1350, "true"},
			{"CUP_arifle_AK12_GP34_arid", 1350, "true"},
			{"CUP_arifle_AK12_GP34_lush", 1350, "true"},
			{"CUP_arifle_AK12_GP34_snowtiger", 1350, "true"},
			{"CUP_arifle_AK12_GP34_tiger", 1350, "true"},
			{"CUP_arifle_AK12_GP34_bicolor", 1350, "true"},
			{"CUP_arifle_AK12_GP34_wood", 1350, "true"},
			{"CUP_arifle_AK12_GP34_winter", 1350, "true"},
			{"CUP_arifle_AK12_GP34_tan", 1350, "true"},
			{"CUP_arifle_AK15_black", 1200, "true"},
			{"CUP_arifle_AK15_AFG_arid", 1300, "true"},
			{"CUP_arifle_AK15_AFG_lush", 1300, "true"},
			{"CUP_arifle_AK15_AFG_tan", 1300, "true"},
			{"CUP_arifle_AK15_AFG_snowtiger", 1300, "true"},
			{"CUP_arifle_AK15_AFG_tiger", 1300, "true"},
			{"CUP_arifle_AK15_AFG_bicolor", 1300, "true"},
			{"CUP_arifle_AK15_AFG_winter", 1300, "true"},
			{"CUP_arifle_AK15_AFG_wood", 1300, "true"},
			{"CUP_arifle_AK15_arid", 1300, "true"},
			{"CUP_arifle_AK15_VG_arid", 1200, "true"},
			{"CUP_arifle_AK15_VG_lush", 1400, "true"},
			{"CUP_arifle_AK15_VG_tan", 1400, "true"},
			{"CUP_arifle_AK15_VG_snowtiger", 1400, "true"},
			{"CUP_arifle_AK15_AFG_black", 1400, "true"},
			{"CUP_arifle_AK15_VG_tiger", 1400, "true"},
			{"CUP_arifle_AK15_VG_bicolor", 1400, "true"},
			{"CUP_arifle_AK15_VG_winter", 1400, "true"},
			{"CUP_arifle_AK15_VG_wood", 1400, "true"},
			{"CUP_arifle_AK15_VG_black", 1400, "true"},
			{"CUP_arifle_AK15_lush", 1200, "true"},
			{"CUP_arifle_AK15_tan", 1200, "true"},
			{"CUP_arifle_AK15_snowtiger", 1200, "true"},
			{"CUP_arifle_AK15_tiger", 1200, "true"},
			{"CUP_arifle_AK15_bicolor", 1200, "true"},
			{"CUP_arifle_AK15_winter", 1200, "true"},
			{"CUP_arifle_AK15_wood", 1200, "true"},
			{"CUP_arifle_AK15_GP34_arid", 1350, "true"},
			{"CUP_arifle_AK15_GP34_lush", 1350, "true"},
			{"CUP_arifle_AK15_GP34_tan", 1350, "true"},
			{"CUP_arifle_AK15_GP34_snowtiger", 1350, "true"},
			{"CUP_arifle_AK15_GP34_black", 1350, "true"},
			{"CUP_arifle_AK15_GP34_tiger", 1350, "true"},
			{"CUP_arifle_AK15_GP34_winter", 1350, "true"},
			{"CUP_arifle_AK15_GP34_bicolor", 1350, "true"},
			{"CUP_arifle_AK15_GP34_wood", 1350, "true"},
			{"CUP_arifle_AK19_AFG_arid", 1300, "true"},
			{"CUP_arifle_AK19_black", 1200, "true"},
			{"CUP_arifle_AK19_AFG_lush", 1300, "true"},
			{"CUP_arifle_AK19_AFG_tan", 1300, "true"},
			{"CUP_arifle_AK19_AFG_snowtiger", 1300, "true"},
			{"CUP_arifle_AK19_AFG_bicolor", 1300, "true"},
			{"CUP_arifle_AK19_AFG_tiger", 1300, "true"},
			{"CUP_arifle_AK19_AFG_wood", 1300, "true"},
			{"CUP_arifle_AK19_AFG_winter", 1300, "true"},
			{"CUP_arifle_AK19_AFG_black", 1300, "true"},
			{"CUP_arifle_AK19_arid", 1200, "true"},
			{"CUP_arifle_AK19_VG_arid", 1400, "true"},
			{"CUP_arifle_AK19_VG_lush", 1400, "true"},
			{"CUP_arifle_AK19_VG_tan", 1400, "true"},
			{"CUP_arifle_AK19_VG_snowtiger", 1400, "true"},
			{"CUP_arifle_AK19_VG_bicolor", 1400, "true"},
			{"CUP_arifle_AK19_VG_winter", 1400, "true"},
			{"CUP_arifle_AK19_VG_tiger", 1400, "true"},
			{"CUP_arifle_AK19_VG_wood", 1400, "true"},
			{"CUP_arifle_AK19_VG_black", 1400, "true"},
			{"CUP_arifle_AK19_lush", 1200, "true"},
			{"CUP_arifle_AK19_snowtiger", 1200, "true"},
			{"CUP_arifle_AK19_tan", 1200, "true"},
			{"CUP_arifle_AK19_bicolor", 1200, "true"},
			{"CUP_arifle_AK19_winter", 1200, "true"},
			{"CUP_arifle_AK19_wood", 1200, "true"},
			{"CUP_arifle_AK19_tiger", 1200, "true"},
			{"CUP_arifle_AK19_GP34_black", 1350, "true"},
			{"CUP_arifle_AK19_GP34_arid", 1350, "true"},
			{"CUP_arifle_AK19_GP34_lush", 1350, "true"},
			{"CUP_arifle_AK19_GP34_tan", 1350, "true"},
			{"CUP_arifle_AK19_GP34_snowtiger", 1350, "true"},
			{"CUP_arifle_AK19_GP34_tiger", 1350, "true"},
			{"CUP_arifle_AK19_GP34_bicolor", 1350, "true"},
			{"CUP_arifle_AK19_GP34_winter", 1350, "true"},
			{"CUP_arifle_AK19_GP34_wood", 1350, "true"}
		};
	};
	
	class MachineGun
	{
		displayName = "$STR_HG_SHOP_MACHINE_GUN";
		content[] =
		{
			{"CUP_arifle_Sa58_Klec", 400, "true"},
			{"CUP_arifle_Sa58_Klec_rearris", 450, "true"},
			{"CUP_arifle_Sa58_Klec_frontris", 450, "true"},
			{"CUP_arifle_Sa58_Klec_ris", 500, "true"},
			{"CUP_lmg_UK59", 200, "true"},
			{"CUP_lmg_PKMN", 500, "true"},
			{"CUP_lmg_PKM", 400, "true"},
			{"CUP_lmg_PKM_B50_vfg", 800, "true"},
			{"CUP_lmg_PKM_front_rail_B50_vfg", 800, "true"},
			{"CUP_lmg_PKM_top_rail", 1400, "true"},
			{"CUP_lmg_PKM_top_rail_B50_vfg", 2800, "true"},
			{"CUP_lmg_Pecheneg", 400, "true"},
			{"CUP_lmg_Pecheneg_B50_vfg", 800, "true"},
			{"CUP_lmg_Pecheneg_woodland", 400, "true"},
			{"CUP_lmg_Pecheneg_desert", 400, "true"},
			{"CUP_lmg_Pecheneg_top_rail", 1400, "true"},
			{"CUP_lmg_Pecheneg_top_rail_B50_vfg", 2200, "true"},
			{"CUP_arifle_RPK74", 900, "true"},
			{"CUP_arifle_RPK74_top_rail", 1900, "true"},
			{"CUP_arifle_RPK74M", 1100, "true"},
			{"CUP_arifle_RPK74M_railed", 2200, "true"},
			{"CUP_arifle_RPK74M_top_rail", 2000, "true"},
			{"CUP_arifle_RPK74_45", 900, "true"}
		};
	};
	
	class SubmachineGun
	{
		displayName = "$STR_HG_SHOP_SUB_MACHINE_GUN";
		content[] =
		{
			{"CUP_arifle_SR3M_Vikhr", 140, "true"},
			{"CUP_arifle_SR3M_Vikhr_VFG", 180, "true"},
			{"CUP_arifle_SR3M_Vikhr_VFG_top_rail", 1400, "true"},
			{"CUP_arifle_SR3M_Vikhr_top_rail", 1800, "true"},
			{"CUP_smg_UZI", 120, "true"},
			{"CUP_smg_vityaz", 140, "true"},
			{"CUP_smg_vityaz_vfg", 180, "true"},
			{"CUP_smg_vityaz_vfg_front_rail", 1400, "true"},
			{"CUP_smg_vityaz_top_rail", 200, "true"},
			{"CUP_smg_vityaz_vfg_top_rail", 250, "true"}
		};
	};
	
	class SniperRifle
	{
		displayName = "$STR_HG_SHOP_SNIPER_RIFLE";
		content[] =
		{
			{"srifle_dmr_04_f",25000,"true"}
		};
	};
};
