/*
    Author - HoverGuy
    Website - https://northernimpulse.com

    Defines available items shops

	class YourShopClass - Used as a param for the call, basically the shop you want to display
	{
		conditionToAccess - STRING - Condition that must return either true or false, if true the player will have access to the shop

		class YourShopCategory - Shop category, can be whatever you want
		{
			displayName - STRING - Category display name
			items - ARRAY OF ARRAYS - Shop content
			|- 0 - STRING - Classname
			|- 1 - INTEGER - Price
			|- 2 - STRING - Condition that must return either true or false, if true the item appears in the list else no
		};
	};
*/

class HG_DefaultShop // HG_DefaultShop is just a placeholder for testing purposes, you can delete it completely and make your own
{
	conditionToAccess = "true"; // Example: "(playerSide in [west,independent]) AND ((rank player) isEqualTo 'COLONEL')"

	class Items
	{
	    displayName = "$STR_HG_SHOP_ITEMS";
		items[] =
		{
		{"ItemWatch",50,"true"},
		{"ItemCompass",50,"true"},
		{"ItemGPS",50,"true"},
		{"ItemMap",50,"true"},
		{"O_UavTerminal", 1000, "true"},
		{"ChemicalDetector_01_watch_F", 200, "true"},
		{"ACE_Altimeter", 200, "true"},
		{"TFAR_microdagr", 100, "true"},
		{"TFAR_fadak", 50, "true"},
		{"ACE_UAVBattery", 400, "true"},
		{"ACE_M26_Clacker", 150, "true"},
		{"ACE_Clacker", 150, "true"},
		{"ACE_IR_Strobe_Item", 10, "true"},
		{"ACE_SpottingScope", 50, "true"},
		{"ACE_MapTools", 75, "true"},
		{"ACE_DefusalKit", 340, "true"},
		{"ACE_wirecutter", 200, "true"},
		{"ACE_RangeCard", 30, "true"},
		{"ACE_Tripod", 40, "true"},
		{"ACE_EntrenchingTool", 150, "true"},
		{"ACE_Flashlight_KSF1", 40, "true"},
		{"ACE_Kestrel4500", 45, "true"},
		{"WBK_HeadLampItem", 15, "true"},
		{"ACE_RangeTable_82mm", 7, "true"},
		{"ToolKit", 90, "true"},
		{"ACE_CableTie", 3, "true"}
		};
	};

	class Magazines
	{
	    displayName = "$STR_HG_SHOP_MAGAZINES";
		items[] =
		{
		    {"30Rnd_65x39_caseless_mag",250,"true"},
            {"16Rnd_9x21_Mag",75,"true"},
	        {"30Rnd_9x21_Mag",150,"true"}
		};
	};

	class OtherAttachments
	{
	    displayName = "$STR_HG_FIXTURE_ON_THE_BAR";
		items[] =
		{
		{"CUP_acc_Zenit_2DS", 40, "true"},
		{"CUP_acc_LCU_PM_Laser", 400, "true"},
		{"ACE_acc_pointer_green", 330, "true"},
		{"CUP_acc_Flashlight_MP5", 600, "true"},
		{"CUP_acc_Flashlight_MP5SD", 800, "true"},
		{"CUP_SVD_camo_g", 110, "true"},
		{"CUP_SVD_camo_g_half", 140, "true"},
		{"CUP_SVD_camo_d", 110, "true"},
		{"CUP_SVD_camo_d_half", 150, "true"},
		{"CUP_acc_Flashlight", 150, "true"},
		{"CUP_acc_Flashlight_desert", 150, "true"},
		{"CUP_acc_Flashlight_wdl", 150, "true"},
		{"CUP_Mxx_camo", 650, "true"},
		{"CUP_acc_Glock17_Flashlight",200, "true"},
		{"CUP_Mxx_camo_half", 460, "true"},
		{"ACE_SPIR", 200, "true"},
		{"CUP_acc_XM8_light_module", 230, "true"},
		{"CUP_acc_LLM", 230, "true"},
		{"CUP_acc_LLM_black", 230, "true"},
		{"CUP_acc_LLM_od", 230, "true"},
		{"CUP_acc_LLM01_L", 140, "true"},
		{"CUP_acc_LLM01_hex_L", 140, "true"},
		{"CUP_acc_LLM01_coyote_L", 140, "true"},
		{"CUP_acc_LLM01_desert_L", 140, "true"},
		{"CUP_acc_LLM01_od_L", 140, "true"}
};
	};

	class Scopes
	{
	    displayName = "$STR_HG_SHOP_SCOPES";
		items[] =
		{
		{"CUP_optic_OKP_7", 25,"true"},
		{"CUP_optic_OKP_7_w", 25,"true"},
		{"CUP_optic_OKP_7_d", 25,"true"},
		{"CUP_optic_MRad", 40,"true"},
		{"CUP_optic_OKP_7_rail", 70,"true"},
		{"CUP_optic_OKP_7_w_rail", 70,"true"},
		{"CUP_optic_OKP_7_d_rail", 70,"true"},
		{"CUP_optic_Kobra", 50,"true"},
		{"CUP_optic_1p63", 15,"true"},
		{"CUP_optic_ekp_8_02", 15,"true"},
		{"CUP_optic_AC11704_Black", 70,"true"},
		{"CUP_optic_AC11704_Coyote", 70,"true"},
		{"CUP_optic_AC11704_Jungle", 70,"true"},
		{"CUP_optic_AC11704_OD", 70,"true"},
		{"CUP_optic_AC11704_Tan", 70,"true"},
		{"CUP_optic_HoloWdl", 80,"true"},
		{"CUP_optic_HoloDesert", 80,"true"},
		{"CUP_optic_HoloBlack", 80,"true"},
		{"optic_Holosight_lush_F", 80,"true"},
		{"CUP_optic_1P87_RIS_woodland", 80,"true"},
		{"CUP_optic_1P87_RIS", 80,"true"},
		{"CUP_optic_1P87_RIS_desert", 80,"true"},
		{"CUP_optic_Eotech553_Coyote", 100,"true"},
		{"CUP_optic_Eotech533Grey", 100,"true"},
		{"CUP_optic_Eotech533", 100,"true"},
		{"CUP_optic_Eotech553_Black", 100,"true"},
		{"CUP_optic_Eotech553_OD", 100,"true"},
		{"CUP_optic_MARS", 120,"true"},
		{"CUP_optic_MARS_OD", 120,"true"},
		{"CUP_optic_MARS_tan", 120,"true"},
		{"CUP_optic_PechenegScope", 300,"true"},
		{"CUP_optic_NSPU_RPG", 450,"true"},
		{"CUP_optic_NSPU", 400,"true"},
		{"CUP_optic_PGO7V", 200,"true"},
		{"CUP_optic_PGO7V2",200,"true"},
		{"CUP_optic_PGO7V3", 200,"true"},
		{"CUP_optic_PEM", 1000,"true"},
		{"CUP_optic_GrozaScope", 500,"true"},
		{"CUP_optic_PSO_1_open", 180,"true"},
		{"CUP_optic_PSO_1", 200,"true"},
		{"CUP_optic_PSO_1_AK_open", 180,"true"},
		{"CUP_optic_PSO_1_AK", 200,"true"},
		{"CUP_optic_PSO_1_1", 200,"true"},
		{"CUP_optic_PSO_1_1_open", 180,"true"},
		{"CUP_optic_PSO_3", 350,"true"},
		{"CUP_optic_PSO_3_open", 310,"true"},
		{"CUP_optic_GOSHAWK", 3500,"true"},
		{"CUP_optic_GOSHAWK_RIS", 5000,"true"},
		{"CUP_optic_ElcanM145", 700,"true"},
		{"CUP_optic_CWS_NV", 1500,"true"},
		{"CUP_optic_CWS_NV_RDS", 1700,"true"},
		{"CUP_optic_Elcan_SpecterDR_coyote", 1200,"true"},
		{"CUP_optic_Elcan_SpecterDR_black", 1200,"true"},
		{"CUP_optic_Elcan_SpecterDR_KF_coyote", 1200,"true"},
		{"CUP_optic_Elcan_SpecterDR_KF_black", 1200,"true"},
		{"CUP_optic_Elcan_SpecterDR_KF_od", 1200,"true"},
		{"CUP_optic_Elcan_SpecterDR_KF", 1200,"true"},
		{"CUP_optic_Elcan_SpecterDR_od", 1200,"true"},
		{"CUP_optic_Elcan_SpecterDR_RMR_coyote", 1400,"true"},
		{"CUP_optic_Elcan_SpecterDR_RMR_black", 1400,"true"},
		{"CUP_optic_Elcan_SpecterDR_KF_RMR_coyote", 1400,"true"},
		{"CUP_optic_Elcan_SpecterDR_KF_RMR_black", 1400,"true"},
		{"CUP_optic_Elcan_SpecterDR_KF_RMR_od", 1400,"true"},
		{"CUP_optic_Elcan_SpecterDR_KF_RMR", 1400,"true"},
		{"CUP_optic_Elcan_SpecterDR_RMR_od", 1400,"true"},
		{"CUP_optic_Elcan_SpecterDR_RMR", 1400,"true"},
		{"CUP_optic_Elcan_SpecterDR", 1300,"true"},
		{"CUP_optic_Elcan_Coyote", 700,"true"},
		{"CUP_optic_Elcan", 650,"true"},
		{"CUP_optic_Elcan_OD", 700,"true"},
		{"CUP_optic_Elcan_reflex_Coyote", 900,"true"},
		{"CUP_optic_Elcan_reflex", 900,"true"},
		{"CUP_optic_Elcan_reflex_OD", 900,"true"},
		{"CUP_optic_G33_HWS_COYOTE", 300,"true"},
		{"CUP_optic_G33_HWS_BLK", 300,"true"},
		{"CUP_optic_G33_HWS_TAN", 300,"true"},
		{"CUP_optic_G33_HWS_OD", 300,"true"},
		{"CUP_optic_HensoldtZO", 400,"true"},
		{"CUP_optic_HensoldtZO_hex", 400,"true"},
		{"CUP_optic_HensoldtZO_coyote", 400,"true"},
		{"CUP_optic_HensoldtZO_low", 400,"true"},
		{"CUP_optic_HensoldtZO_low_hex", 400,"true"},
		{"CUP_optic_HensoldtZO_low_coyote", 400,"true"},
		{"CUP_optic_HensoldtZO_low_desert", 400,"true"},
		{"CUP_optic_HensoldtZO_low_od", 400,"true"},
		{"CUP_optic_HensoldtZO_low_RDS", 600,"true"},
		{"CUP_optic_HensoldtZO_low_RDS_hex", 600,"true"},
		{"CUP_optic_HensoldtZO_low_RDS_coyote", 600,"true"},
		{"CUP_optic_HensoldtZO_low_RDS_desert", 600,"true"},
		{"CUP_optic_HensoldtZO_low_RDS_od", 600,"true"},
		{"CUP_optic_HensoldtZO_desert", 400,"true"},
		{"CUP_optic_HensoldtZO_od", 400,"true"},
		{"CUP_optic_HensoldtZO_RDS", 600,"true"},
		{"CUP_optic_HensoldtZO_RDS_hex", 600,"true"},
		{"CUP_optic_HensoldtZO_RDS_coyote", 600,"true"},
		{"CUP_optic_HensoldtZO_RDS_desert", 600,"true"},
		{"CUP_optic_HensoldtZO_RDS_od", 600,"true"},
		{"CUP_optic_ISM1400A7", 200,"true"},
		{"CUP_optic_ISM1400A7_green", 200,"true"},
		{"CUP_optic_ISM1400A7_tan", 200,"true"},
		{"CUP_optic_ISM1400A7_OD", 200,"true"},
		{"CUP_optic_LeupoldMk4_10x40_LRT_Desert", 2000,"true"},
		{"CUP_optic_LeupoldMk4_10x40_LRT_Woodland", 2000,"true"},
		{"CUP_optic_LeupoldMk4", 2000,"true"},
		{"CUP_optic_LeupoldMk4_MRT_tan", 2000,"true"},
		{"CUP_optic_LeupoldM3LR", 1800,"true"},
		{"CUP_optic_LeupoldMk4_20x40_LRT", 2300,"true"},
		{"CUP_optic_LeupoldMk4_25x50_LRT_SNOW", 2300,"true"},
		{"CUP_optic_LeupoldMk4_25x50_LRT_WOODLAND", 2300,"true"},
		{"CUP_optic_LeupoldMk4_25x50_LRT_DESERT", 2300,"true"},
		{"CUP_optic_LeupoldMk4_25x50_LRT", 2300,"true"},
		{"CUP_optic_LeupoldMk4_CQ_T", 1500,"true"},
		{"CUP_optic_Leupold_VX3", 2300,"true"},
		{"CUP_optic_CompM2_Coyote", 1100,"true"},
		{"CUP_optic_CompM2_Woodland2", 1100,"true"},
		{"CUP_optic_CompM2_Woodland", 1100,"true"},
		{"CUP_optic_CompM2_Desert", 1100,"true"},
		{"CUP_optic_CompM2_Black", 1100,"true"},
		{"CUP_optic_CompM2_OD", 1100,"true"},
		{"CUP_optic_AIMM_COMPM2_TAN", 2200,"true"},
		{"CUP_optic_AIMM_COMPM2_BLK", 2200,"true"},
		{"CUP_optic_AIMM_COMPM2_OD", 2200,"true"},
		{"CUP_optic_CompM2_low_coyote", 1100,"true"},
		{"CUP_optic_CompM2_low", 1100,"true"},
		{"CUP_optic_CompM2_low_OD", 1100,"true"},
		{"CUP_optic_ZDDot", 200,"true"},
		{"CUP_optic_MEPRO", 220,"true"},
		{"CUP_optic_MEPRO_moa_clear", 220,"true"},
		{"CUP_optic_MEPRO_openx_orange", 220,"true"},
		{"CUP_optic_MEPRO_tri_clear", 220,"true"},
		{"CUP_optic_SB_11_4x20_PM_tan", 2800,"true"},
		{"CUP_optic_SB_11_4x20_PM_od", 2800,"true"},
		{"CUP_optic_SB_11_4x20_PM", 2800,"true"},
		{"CUP_optic_SUSAT", 600,"true"},
		{"CUP_optic_ACOG_TA01B_Black", 1300,"true"},
		{"CUP_optic_ACOG_TA01B_Coyote", 1300,"true"},
		{"CUP_optic_ACOG_TA01B_Tropic", 1300,"true"},
		{"CUP_optic_ACOG_TA01B_OD", 1300,"true"},
		{"CUP_optic_ACOG_TA01B_RMR_Black", 1500,"true"},
		{"CUP_optic_ACOG_TA01B_RMR_Coyote", 1500,"true"},
		{"CUP_optic_ACOG_TA01B_RMR_Tropic", 1500,"true"},
		{"CUP_optic_ACOG_TA01B_RMR_OD", 1500,"true"},
		{"CUP_optic_ACOG_TA01B_RMR_Tan", 1500,"true"},
		{"CUP_optic_ACOG_TA01B_Tan", 1300,"true"},
		{"CUP_optic_RCO", 1300,"true"},
		{"CUP_optic_RCO_desert", 1300,"true"},
		{"CUP_optic_ACOG_TA01NSN_Tropic", 1500,"true"},
		{"CUP_optic_ACOG_TA01NSN_OD", 1500,"true"},
		{"CUP_optic_ACOG_TA01NSN_RMR_Black", 1500,"true"},
		{"CUP_optic_ACOG_TA01NSN_RMR_Coyote", 1500,"true"},
		{"CUP_optic_ACOG_TA01NSN_RMR_Tropic", 1500,"true"},
		{"CUP_optic_ACOG_TA01NSN_RMR_OD", 1500,"true"},
		{"CUP_optic_ACOG_TA01NSN_RMR_Tan", 1300,"true"},
		{"CUP_optic_ACOG2", 2000,"true"},
		{"CUP_optic_ACOG_TA31_KF_Wood", 2000,"true"},
		{"CUP_optic_ACOG_TA31_KF_Desert", 2000,"true"},
		{"CUP_optic_ACOG_TA31_KF", 2000,"true"},
		{"CUP_optic_ACOG_Reflex_Wood", 2300,"true"},
		{"CUP_optic_ACOG_Reflex_Desert", 2300,"true"},
		{"CUP_optic_ACOG", 2300,"true"},
		{"CUP_optic_ACOG_TA648_308_Black", 2700,"true"},
		{"CUP_optic_ACOG_TA648_308_coyo", 2700,"true"},
		{"CUP_optic_ACOG_TA648_308_Wdl", 2700,"true"},
		{"CUP_optic_ACOG_TA648_308_Desert", 2700,"true"},
		{"CUP_optic_ACOG_TA648_308_od", 2700,"true"},
		{"CUP_optic_ACOG_TA648_308_RDS_Black", 3000,"true"},
		{"CUP_optic_ACOG_TA648_308_RDS_coyo", 3000,"true"},
		{"CUP_optic_ACOG_TA648_308_RDS_Wdl", 3000,"true"},
		{"CUP_optic_ACOG_TA648_308_RDS_Desert", 3000,"true"},
		{"CUP_optic_ACOG_TA648_308_RDS_od", 3000,"true"},
		{"CUP_optic_TrijiconRx01_desert", 300,"true"},
		{"CUP_optic_TrijiconRx01_black", 300,"true"},
		{"CUP_optic_TrijiconRx01_kf_desert", 300,"true"},
		{"CUP_optic_TrijiconRx01_kf_black", 300,"true"},
		{"CUP_optic_TrijiconRx01_kf_od", 300,"true"},
		{"CUP_optic_TrijiconRx01_od", 300,"true"},
		{"CUP_optic_VortexRazor_UH1_Coyote", 500,"true"},
		{"CUP_optic_VortexRazor_UH1_Black", 500,"true"},
		{"CUP_optic_VortexRazor_UH1_Khaki", 500,"true"},
		{"CUP_optic_VortexRazor_UH1_Tan", 500,"true"},
		{"CUP_optic_VortexRazor_UH1_OD", 500,"true"}
		};
	};

	class Medicine
	{
			displayName = "$STR_HG_MEDICINE";
		items[] =
		{
		{"ACE_personalAidKit", 500,"true"},
		{"ACE_adenosine", 100,"true"},
		{"ACE_epinephrine", 75,"true"},
		{"ACE_EarPlugs", 20,"true"},
		{"ACE_painkillers", 150,"true"},
		{"ACE_tourniquet", 20,"true"},
		{"ACE_bloodIV", 600,"true"},
		{"ACE_bloodIV_250", 200,"true"},
		{"ACE_bloodIV_500", 300,"true"},
		{"ACE_bodyBag", 50,"true"},
		{"ACE_bodyBag_blue", 50,"true"},
		{"ACE_bodyBag_white", 50,"true"},
		{"ACE_morphine", 50,"true"},
		{"ACE_plasmaIV", 300,"true"},
		{"ACE_plasmaIV_250", 100,"true"},
		{"ACE_plasmaIV_500", 200,"true"},
		{"ACE_elasticBandage", 10,"true"},
		{"ACE_fieldDressing", 10,"true"},
		{"ACE_packingBandage", 10,"true"},
		{"ACE_surgicalKit", 1000,"true"},
		{"ACE_splint", 50,"true"},
		{"ACE_suture", 10,"true"}
		};
	};

	class Muzzles 
	{
  		displayName = "$STR_HG_SHOP_MUZZLES";
  		items[] = 
		{
		{"CUP_muzzle_mfsup_SCAR_L", 2000, "true"},
		{"CUP_muzzle_mfsup_SCAR_H", 3000, "true"},
		{"CUP_muzzle_snds_groza", 10000, "true"},
		{"CUP_muzzle_Bizon", 3000, "true"},
		{"CUP_muzzle_PBS4", 1500, "true"},
		{"CUP_muzzle_PB6P9", 4000, "true"},
		{"CUP_muzzle_snds_SR3M", 2000, "true"},
		{"CUP_muzzle_TGPA", 1700, "true"},
		{"CUP_muzzle_TGPA_woodland", 1700, "true"},
		{"CUP_muzzle_TGPA_desert", 1700, "true"},
		{"CUP_muzzle_snds_UZI", 700, "true"},
		{"CUP_muzzle_snds_socom762rc", 6000, "true"},
		{"CUP_muzzle_snds_M16", 4700, "true"},
		{"CUP_muzzle_snds_M16_desert", 4700, "true"},
		{"CUP_muzzle_snds_M16_camo", 4700, "true"},
		{"CUP_muzzle_snds_M16_coyote", 4700, "true"},
		{"CUP_muzzle_fh_MP5", 1200, "true"},
		{"CUP_muzzle_mfsup_Suppressor_Mac10", 3000, "true"},
		{"CUP_muzzle_snds_M110_black", 12000, "true"},
		{"CUP_muzzle_snds_M110_woodland", 12000, "true"},
		{"CUP_muzzle_snds_FAMAS_Wood", 8000, "true"},
		{"CUP_muzzle_snds_FAMAS", 8000, "true"},
		{"CUP_muzzle_snds_FAMAS_Arid", 8000, "true"},
		{"CUP_muzzle_mfsup_flashhider_Sa58", 4500, "true"},
		{"CUP_muzzle_mfsup_Flashhider_762x51_Tan", 3500, "true"},
		{"CUP_muzzle_mfsup_Flashhider_762x51_OD", 3500, "true"},
		{"CUP_muzzle_mfsup_Flashhider_762x51_Black", 3000, "true"},
		{"CUP_muzzle_mfsup_Flashhider_762x39_Tan", 3000, "true"},
		{"CUP_muzzle_mfsup_Flashhider_762x39_OD", 3000, "true"},
		{"CUP_muzzle_mfsup_Flashhider_762x39_Black", 3000, "true"},
		{"ACE_muzzle_mzls_B", 3000, "true"},
		{"ACE_muzzle_mzls_H", 3000, "true"},
		{"CUP_muzzle_mfsup_Flashhider_556x45_Tan", 2200, "true"},
		{"CUP_muzzle_mfsup_Flashhider_556x45_OD", 2200, "true"},
		{"CUP_muzzle_mfsup_Flashhider_556x45_Black", 2200, "true"},
		{"CUP_muzzle_mfsup_Flashhider_545x39_Tan", 2200, "true"},
		{"CUP_muzzle_mfsup_Flashhider_545x39_OD", 2200, "true"},
		{"CUP_muzzle_mfsup_Flashhider_545x39_Black", 2200, "true"},
		{"ACE_muzzle_mzls_L", 2000, "true"},
		{"ACE_muzzle_mzls_smg_01", 1600, "true"},
		{"ACE_muzzle_mzls_338", 1200, "true"},
		{"CUP_muzzle_mfsup_Flashhider_PK_OD", 3500, "true"},
		{"CUP_muzzle_mfsup_Flashhider_PK_Tan", 3500, "true"},
		{"CUP_muzzle_mfsup_Flashhider_PK_Black", 3500, "true"},
		{"CUP_muzzle_snds_KZRZP_AK762_desert", 5000, "true"},
		{"CUP_muzzle_snds_KZRZP_AK762_woodland", 5000, "true"},
		{"CUP_muzzle_snds_KZRZP_AK762", 5000, "true"},
		{"CUP_muzzle_snds_KZRZP_AK545_woodland", 4000, "true"},
		{"CUP_muzzle_snds_KZRZP_AK545_desert", 4000, "true"},
		{"CUP_muzzle_snds_KZRZP_AK545", 4000, "true"},
		{"CUP_muzzle_snds_KZRZP_SVD_desert", 6000, "true"},
		{"CUP_muzzle_snds_KZRZP_SVD_woodland", 6000, "true"},
		{"CUP_muzzle_snds_KZRZP_SVD", 6000, "true"},
		{"CUP_muzzle_snds_KZRZP_PK_desert", 6000, "true"},
		{"CUP_muzzle_snds_KZRZP_PK_woodland", 6000, "true"},
		{"CUP_muzzle_snds_KZRZP_PK", 6000, "true"},
		{"CUP_muzzle_snds_XM8", 12000, "true"},
		{"CUP_muzzle_snds_SA61", 1488, "true"},
		{"CUP_muzzle_snds_mk23", 1488, "true"},
		{"CUP_muzzle_snds_SCAR_H", 10000, "true"},
		{"CUP_muzzle_snds_SCAR_L", 7000, "true"},
		{"CUP_muzzle_snds_Mk12", 14000, "true"},
		{"CUP_muzzle_snds_M110", 12000, "true"},
		{"CUP_muzzle_snds_L85", 10000, "true"},
		{"CUP_muzzle_snds_AWM", 15000, "true"},
		{"CUP_muzzle_snds_G36_black", 5500, "true"},
		{"CUP_muzzle_snds_G36_desert", 5500, "true"},
		{"CUP_muzzle_snds_G36_wood", 5500, "true"},
		{"CUP_muzzle_snds_G36_hex", 5500, "true"},
		{"CUP_muzzle_snds_MicroUzi", 1200, "true"},
		{"CUP_muzzle_snds_M9", 800, "true"},
		{"CUP_muzzle_snds_M14", 6000, "true"},
		{"CUP_muzzle_snds_MP7", 4000, "true"},
		{"CUP_muzzle_snds_MP5", 3000, "true"}
  		};
	};
};
